### PR TITLE
Fixes #127. Added delete support for sink.

### LINKED ISSUE #127: Delete Support for sink
Hello,

In kafka and especially kafka streams a delete is expressed as a null value being published for the specific key that needs to be deleted. I do understand that the current source can't catch deletes as the rows are then gone and wont come up as query results. But the Sink side should probably be able to handle deletes correctly. Especially if you want to store the results of a streams application in a relational database.

Best

### LINKED ISSUE #607: delete support for sink connector
jdbc sink connector deletes are disabled，what are the methods set deletes enabked。
i have tried use deleted.enabled=true，but it does not work。

### PR DESCRIPTION
**Pull request by andybryant**
A record with `null` value is considered a tombstone event and result in deleting the corresponding row in the destination table.
Deletes are disabled by default. Set config `delete.enabled` to `true` to enable. Also requires `pk.mode = record_key` otherwise it can't find the record to delete.

Tested against Postgres

Fixes #607 and fixes #127

### CODE REVIEW

**Comment by rhauch** [comment]
@andybryant thanks for updating the changes and creating this new PR. Very much looking forward to having this feature, but currently the build results show a number of test failures.

File: src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java [hunk 1]
```diff
@@ -102,6 +102,13 @@
       + " table, when possible.";
   private static final String BATCH_SIZE_DISPLAY = "Batch Size";
 
+  public static final String DELETE_ENABLED = "delete.enabled";
+  private static final String DELETE_ENABLED_DEFAULT = "false";
+  private static final String DELETE_ENABLED_DOC =
+      "Whether to treat ``null`` record values as deletes. Requires ``pk.mode`` "
+      + "to be ``record_key``.";
```
Comment (rhauch) [inline src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java]: Because `Validator` only has the context of an individual configuration value, it's not straightforward to validate  one config value (e.g., `pk.mode` must be `record_key`). One technique that works, however, is to add a check in the `JdbcSinkConfig` constructor to check these two config values against this constraint and throw `ConfigException` if they are not compatible. This will help ensure that invalid configurations are caught immediately before the connector is started and without having to figure out why the task failing at a later time.

Also, to help C3 and other GUI tools present valid options to begin with, how about adding
* a `Recommender` implementation for `delete.enabled` that hides it if `pk.mode` is not `record_key`; and
* a `Recommender` for `pk.mode` that recommends only `record_key` if `delete.enabled=true`.

It also may be

File: src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialect.java [hunk 2]
```diff
@@ -360,6 +360,21 @@ String buildUpsertQueryStatement(
...
+   * @param table         the identifier of the table; may not be null
+   * @param keyColumns    the identifiers of the columns in the primary/unique key; may not be null
+   *                      but may be empty
+   * @return the delete statement; may not be null
+   * @throws UnsupportedOperationException if the dialect does not support upserts
+   */
+  String buildDeleteStatement(
+      TableId table,
+      Collection<ColumnId> keyColumns
+  );
```
Comment (rhauch) [inline src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialect.java]: Should this be a default method that throws UnsupportedOperationException? It's possible that other projects depend on this connector and add their own dialect, and adding a non-default method would break those projects. Yeah, it's likely they extend `GenericDatabaseDialect`, but we can't rule it out. Plus, I think this makes sense, too, because by default dialects (that don't extend `GenericDatabaseDialect`) probably won't support deletes anyway.

File: src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java [hunk 3]
```diff
@@ -229,6 +293,26 @@ private String getInsertSql() {
...
 
+  private String getDeleteSql() {
+    String sql = null;
+    if (config.deleteEnabled) {
+      switch (config.pkMode) {
+        case RECORD_KEY:
+          if (fieldsMetadata.keyFieldNames.isEmpty()) {
+            throw new ConnectException("Require primary keys to support delete");
+          }
+          sql = dbDialect.buildDeleteStatement(
```
Comment (rhauch) [inline src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java]: Should we catch `UnsupportedOperationException` and throw a `ConnectException` with a more useful message?

File: src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java [hunk 4]
```diff
@@ -229,6 +293,26 @@ private String getInsertSql() {
...
+              tableId,
+              asColumns(fieldsMetadata.keyFieldNames)
+          );
+          break;
+        default:
+          throw new ConnectException("Deletes are only supported for pk.mode record_key");
```
Comment (rhauch) [inline src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java]: Strictly speaking, this case wouldn't be necessary if Config validation ensures that `config.pkMode == RecordKey` when `config.deleteEnabled`. However, I still think it's good to have, just in case.

File: src/test/java/io/confluent/connect/jdbc/sink/BufferedRecordsTest.java [hunk 5]
```diff
@@ -103,6 +103,123 @@ public void correctBatching() throws SQLException {
...
+
+    assertEquals(Arrays.asList(recordA, recordA, recordADelete), buffer.add(recordB));
+
+    assertEquals(Collections.singletonList(recordB), buffer.add(recordA));
+
+    assertEquals(Collections.singletonList(recordA), buffer.flush());
+  }
+
+  @Test
+  public void insertThenDeleteThenInsertInBatchFlush() throws SQLException {
```
Comment (rhauch) [inline src/test/java/io/confluent/connect/jdbc/sink/BufferedRecordsTest.java]: Aren't here a few other cases that we should consider testing? It'd be great to know how much coverage of  `add(record)` the unit tests have, and whether to add more tests if there are more critical lines not hit by the current tests.

File: src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java [hunk 6]
```diff
@@ -67,64 +77,87 @@ public BufferedRecords(
...
+          insertSql,
+          deleteSql,
+          fieldsMetadata
       );
       close();
-      preparedStatement = connection.prepareStatement(sql);
-      preparedStatementBinder = dbDialect.statementBinder(
-          preparedStatement,
+      // should this be using dbDialect.createPreparedStatement ?
+      updatePreparedStatement = connection.prepareStatement(insertSql);
```
[the remark this answers is not in the document]
Comment (andybryant) [reply src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java]: done

File: src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java (hunk 1 above)
Comment (andybryant) [reply src/main/java/io/confluent/connect/jdbc/sink/JdbcSinkConfig.java]: added recommenders for both and tested locally in C3

File: src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialect.java (hunk 2 above)
Comment (andybryant) [reply src/main/java/io/confluent/connect/jdbc/dialect/DatabaseDialect.java]: good idea - fixed

File: src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java (hunk 3 above)
Comment (andybryant) [reply src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java]: done

File: src/test/java/io/confluent/connect/jdbc/sink/BufferedRecordsTest.java (hunk 5 above)
Comment (andybryant) [reply src/test/java/io/confluent/connect/jdbc/sink/BufferedRecordsTest.java]: added a few extra tests in latest commit. Let me know if you can think of any other missing scenarios

**Comment by andybryant** [comment]
@rhauch - thanks for reviewing. I've pushing a new commit aimed at addressing your review suggestions. Looks like Jenkins is happy. Let me know if anything else is outstanding. Cheers Andy

**Comment by nghyjohn** [comment]
I have tried to delete record on mysql,
while doing sink, I have used TimestampConverter for my last_update field.
Error shows seems it is because delete action will have null in after,
any suggestions?

[2019-04-30 08:48:45,271] ERROR WorkerSinkTask{id=mysql-jdbc-sink-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask:177)
org.apache.kafka.connect.errors.ConnectException: Tolerance exceeded in error handler
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:178)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execute(RetryWithToleranceOperator.java:104)
        at org.apache.kafka.connect.runtime.TransformationChain.apply(TransformationChain.java:50)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertAndTransformRecord(WorkerSinkTask.java:506)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:464)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:320)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:224)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:192)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.kafka.connect.errors.DataException: Only Struct objects supported for [converting timestamp formats], found: null
        at org.apache.kafka.connect.transforms.util.Requirements.requireStruct(Requirements.java:52)
        at org.apache.kafka.connect.transforms.TimestampConverter.applyWithSchema(TimestampConverter.java:336)
        at org.apache.kafka.connect.transforms.TimestampConverter.apply(TimestampConverter.java:275)
        at org.apache.kafka.connect.runtime.TransformationChain.lambda$apply$0(TransformationChain.java:50)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndRetry(RetryWithToleranceOperator.java:128)
        at org.apache.kafka.connect.runtime.errors.RetryWithToleranceOperator.execAndHandleError(RetryWithToleranceOperator.java:162)
        ... 14 more
[2019-04-30 08:48:45,276] ERROR WorkerSinkTask{id=mysql-jdbc-sink-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:178)

**Comment by andybryant** [comment]
@rhauch - any chance you'll get some time to review the latest update? I'd hate for this PR to go stale too.
Thx Andy

**Comment by andybryant** [comment]
@nghyjohn - the transforms are performed before the connector is called (you can see it's not in the stacktrace at all). So for this setup to work, you would need all your transforms to not fail on null message values. It would be nice if there was an elegant way to do this but I'm not aware of one. In your case, you could write a wrapper transform that forwards messages with null values, otherwise it delegates to the standard TimestampConverter.

**Comment by devshawn** [comment]
@andybryant @rhauch - any updates on this PR? We need this feature for an upcoming project and I'm trying to avoid forking and building this.

**Comment by bigkraig** [comment]
@rhauch friendly ping

**Comment by rhauch** [comment]
Merging to the `5.3.x` branch for inclusion in the upcoming CP 5.3.0. Also forward merged to `master`.

File: src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java [hunk 7]
```diff
@@ -67,64 +77,86 @@ public BufferedRecords(
...
-        record.valueSchema()
-    );
+    final List<SinkRecord> flushed = new ArrayList<>();
+
+    boolean schemaChanged = false;
+    if (!Objects.equals(keySchema, record.keySchema())) {
+      keySchema = record.keySchema();
+      schemaChanged = true;
+    }
+    if (isNull(record.valueSchema())) {
```
Comment (anthavio) [inline src/main/java/io/confluent/connect/jdbc/sink/BufferedRecords.java]: Oddly even when record.value() returns null, record.valueSchema() returns NOT null for me

**Comment by limadelrey** [comment]
> Merging to the `5.3.x` branch for inclusion in the upcoming CP 5.3.0. Also forward merged to `master`.

When is CP 5.3.0 expected to launch?

**Comment by helpermethod** [comment]
Is this already part of the 5.3.0 beta-releases?

**Comment by helpermethod** [comment]
For anyone who is struggling with using the `5.3.0` release:

If you are using JSON both the `payload` and the `schema` attributes of the `value` need to be set to `null`.
