### PR TITLE
CC-311: support for Decimal logical type as incrementing column

### LINKED ISSUE #31: Issue with Oracle column type NUMBER set as "Incrementing Column" in Kafka Connect
Kafka-connect-jdbc program has an issue with Oracle Table that has a Primary Key of Type NUMBER and if we use that for Column as Incrementing (in the mode settings of the Kafka-Connect program).

It appears (from our debugging efforts) we see that NUMBER => java.math.BigDecimal => NUMERIC => BYTES in the kafka-connect-jdbc code. Essentially, the SchemaBuilder.java sets it to Type.BYTES.

And as result, we see the error "Invalid type of Incrementing column: BYTES" when we connect to the Oracle Database. This is a rather severe limitation for the Kafka Connect to be able to work with Oracle Database as most of the PK columns are of type NUMBER

Steps to Reproduce this Issue:

+ Set-up a table in Oracle 

<pre><code>create table TEST_KAFKA_CONNECT {
KAKFA_PK NUMBER not null, UPDATED_AT timestamp not null } </code></pre>

+ Configure the Kafka-Connect

<pre><code>mode=timestamp+incrementing
incrementing.column.name=KAKFA_PK
timestamp.column.name=UPDATED_AT </code></pre>

In the Kafka-Connect-JDBC use the Oracle's JDBC driver (tested with Oracle 11.2.0.2.0; driver corresponding Oracle JDBC driver available here: http://www.oracle.com/technetwork/apps-tech/jdbc-112010-090769.html

### PR DESCRIPTION
**Pull request by shikhar**
Only supported when the scale is 0 (i.e. it is an integer) and <= Long.MAX_VALUE, so we can continue storing it as a long for implementation simplicity

Fixes #31 and #125

### CODE REVIEW

**Comment by shikhar** [comment]
@confluentinc/connect for review

File: src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java [hunk 1]
```diff
@@ -229,6 +202,56 @@ public SourceRecord extractRecord() throws SQLException {
...
+      if (incrementingColumnValue == null) {
+        throw new ConnectException("Null value for incrementing column of type: " + incrementingColumnSchema.type());
+      } else if (isIntegralPrimitiveType(incrementingColumnValue)) {
+        extractedId = ((Number) incrementingColumnValue).longValue();
+      } else if (incrementingColumnSchema.name() != null && incrementingColumnSchema.name().equals(Decimal.LOGICAL_NAME)) {
+        final BigDecimal decimal = ((BigDecimal) incrementingColumnValue);
+        if (decimal.compareTo(LONG_MAX_VALUE_AS_BIGDEC) > 0) {
+          throw new ConnectException("Decimal value for incrementing column exceeded Long.MAX_VALUE");
+        }
+        if (decimal.scale() != 0) {
```
Comment (ewencp) [inline src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java]: An alternative to these restrictions would be to just make `TimestampIncrementingOffset` use a `BigDecimal` and convert the other types (or even make it a composite where you can choose the `long` or the `BigDecimal`. Any reason not to be a bit more liberal by doing that? Performance is the only reason I can think of.

File: src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java [hunk 2]
```diff
@@ -229,6 +202,56 @@ public SourceRecord extractRecord() throws SQLException {
...
+      assert incrementingOffset == -1L || extractedId > incrementingOffset || timestampColumn != null;
+    } else {
+      extractedId = null;
+    }
+
+    return new TimestampIncrementingOffset(extractedTimestamp, extractedId);
+  }
+
+  private boolean isIntegralPrimitiveType(Object incrementingColumnValue) {
+    return incrementingColumnValue instanceof Long
```
Comment (ewencp) [inline src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java]: Probably doesn't matter much in practice, but any reason we switched to checking the value rather than the schema?

File: src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java (hunk 1 above)
Comment (shikhar) [inline src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java]: I was hesitant to store `BigDecimal` when it's some other int type because wasn't sure if JDBC drivers would handle `statement.setBigDecimal()` well for such columns.

BTW, I tried to be more general in a local iteration by storing `Comparable`, in fact even including support for `String` types like in #97 but abandoned after complexity around default values. I have an idea now of how to handle that though, so I'll give this another go.

Comment (shikhar) [inline src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java]: Backwards compatibility is another concern to take care of... so we should probably always map to `Long` for any of the currently supported int types.

Comment (ewencp) [inline src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java]: Wait, this isn't going to get stored in the database, right? This is in the source so we are extracting it. I think the major difference would be that the offsets would change from their integer type to `Decimal`.

Comment (shikhar) [inline src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java]: > so I'll give this another go.

Er, re-abandoned. The issue is, if there is no existing stored offset, you have a `null` but no type. While a sensible default value can be determined ("" for string, -1 for numbers..), need type-info at bind-time.

I think happy with the solution for now. We could expand support to all `Number` types rather than just upto `Long.MAX_VALUE` if there is a request for it.

Comment (shikhar) [inline src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java]: > Wait, this isn't going to get stored in the database, right? This is in the source so we are extracting it.

It gets stored in the offset storage, and used for range queries

Comment (ewencp) [inline src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java]: Ok, makes sense.

File: src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java (hunk 2 above)
Comment (shikhar) [inline src/main/java/io/confluent/connect/jdbc/source/TimestampIncrementingTableQuerier.java]: No good reason :-) Can't recall how I ended up switching to `instanceof`... shouldn't matter as you said
