### PR TITLE
Fix Postgres OOM by limiting fetch size

### LINKED ISSUE #34: java.lang.OutOfMemoryError
I running kafka-connect jdbc on one table, for the first time, and I am quickly running out of memory even though I have set:

```
batch.max.rows = 1
tasks.max = 1
```

It looks like the batch limit is not being effective in my case (I am running it against a postgres database). 

Does the batch limit apply the very first time kafka-connect runs?

### PR DESCRIPTION
**Pull request by gharris1727**
This PR adds an integration test with an embedded postgres instance.
There are three tests:
1. Verify that the test setup produces OOM exceptions with large batch sizes.
2. Verify that the test setup does _not_ produce OOM exceptions with small batch sizes.
3. Verify that tables are not left locked when autoCommit is disabled. 

Test 3 addresses a side-effect of autoCommit that was called out in #466, where read-only queries with autoCommit disabled would leave open locks on the database. This test verifies that the `JdbcSourceTask` does not leave open locks from any operations.

#466 specifically observed that the TableMonitorThread would leave open locks if auto-commit was disabled on that connection. This PR circumvents that issue by leaving the TableMonitorThread connection as-is, with autoCommit enabled. There are no tests covering the Connector or TableMonitorThread, because the behavior of those classes is unaffected by these changes. A connector test would also have some extra complication as the TableMonitorThread is asynchronous.

Fixes #34 .

### CODE REVIEW

File: src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java [hunk 1]
```diff
@@ -107,12 +109,24 @@ public boolean next() throws SQLException {
...
     schemaMapping = null;
     lastUpdate = now;
   }
 
+  private void releaseLocksQuietly() {
+    if (db != null) {
+      try {
+        db.commit();
+      } catch (SQLException e) {
+        // intentionally ignored
```
Comment (levzem) [inline src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java]: maybe `log.warn()`?

File: src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java [hunk 2]
```diff
@@ -99,6 +99,8 @@ public void start(Map<String, String> properties) {
 
     cachedConnectionProvider = connectionProvider(maxConnAttempts, retryBackoff);
 
+    disableAutoCommit(cachedConnectionProvider.getConnection());
```
Comment (levzem) [inline src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java]: should we not renable autocommit after every statement - isn't there times when we do need autocommit?

Comment (gharris1727) [reply src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java]: In a single-threaded scenario, we could swap autocommit on and off. I initially thought it would be easier to follow if it was always disabled, and then do explicit commits everywhere.
But seeing as the only other query made in the task (other than the main query) is in `validateNonNullable`, which is only called during the start() method. I could move the disableAutoCommit after the validateNonNullable, and remove the explicit commit there.

I think after the task startup, it's simpler to leave autoCommit disabled, and then call commit explicitly at the conclusion of each query.

File: src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java (hunk 1 above)
Comment (gharris1727) [reply src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java]: `// intentionally ignored` was the style at the time

**Comment by gharris1727** [comment]
Note that `io.zonky.test:embedded-postgres` is Apache 2.0 licensed.

File: src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java [hunk 3]
```diff
@@ -107,12 +109,24 @@ public boolean next() throws SQLException {
   public void reset(long now) {
     closeResultSetQuietly();
     closeStatementQuietly();
+    releaseLocksQuietly();
```
Comment (wicknicks) [inline src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java]: should this be in a finally block, in case any of the above fail?

File: src/test/java/io/confluent/connect/jdbc/source/integration/PostgresOOMIT.java [hunk 4]
```diff
@@ -0,0 +1,163 @@
...
+              row.append(rs.getObject(i));
+              row.append("\t");
+            }
+            log.debug(row.toString());
+          }
+        }
+      }
+    }
+    assertEquals("Found idle locks left open", 0, count);
+    log.info("No locks found");
```
Comment (wicknicks) [inline src/test/java/io/confluent/connect/jdbc/source/integration/PostgresOOMIT.java]: we usually don't have log statements in tests because they are mostly run in jenkins (no one is watching), and if there are no asserts, then it is assumed that the scenario they are testing did not error.

File: src/test/java/io/confluent/connect/jdbc/source/integration/PostgresOOMIT.java [hunk 5]
```diff
@@ -0,0 +1,163 @@
...
+    props.put(JdbcSourceConnectorConfig.CONNECTION_USER_CONFIG, "postgres");
+    props.put(JdbcSourceConnectorConfig.MODE_CONFIG, JdbcSourceConnectorConfig.MODE_BULK);
+    props.put(JdbcSourceTaskConfig.TOPIC_PREFIX_CONFIG, "topic_");
+  }
+
+  public void startTask() {
+
+    task = new JdbcSourceTask();
+    task.start(props);
+  }
```
Comment (wicknicks) [inline src/test/java/io/confluent/connect/jdbc/source/integration/PostgresOOMIT.java]: do we need to test what happens when the table monitor thread is running in the same JVM as these tasks that are setting auto commit to false?

File: src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java [hunk 6]
```diff
@@ -242,6 +242,7 @@ public void start(Map<String, String> properties) {
       }
     }
 
+    disableAutoCommit(cachedConnectionProvider.getConnection());
```
Comment (javabrett) [inline src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java]: `CachedConnectionProvider#getConnection())` performs a validity-test on the connection instance it caches before returning it.  This may result in a dead connection being discarded and replaced with a new instance:

https://github.com/confluentinc/kafka-connect-jdbc/blob/66307690724f6fe54d0a2bb28bbfe8b30fc6a447/src/main/java/io/confluent/connect/jdbc/util/CachedConnectionProvider.java#L63-L66

Due to the `start()`/`poll()` lifecycle, is it possible that a new connection without auto-commit disabled might become active?  Calls might need to be moved, or the option pushed-down into the connection-provider framework.

File: src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java (hunk 3 above)
Comment (gharris1727) [reply src/main/java/io/confluent/connect/jdbc/source/TableQuerier.java]: All of the other `Quietly` functions here swallow the errors, so they won't fail in this block.

File: src/test/java/io/confluent/connect/jdbc/source/integration/PostgresOOMIT.java (hunk 4 above)
Comment (gharris1727) [reply src/test/java/io/confluent/connect/jdbc/source/integration/PostgresOOMIT.java]: This was a debugging statement for me, the assert above it captures what I want the function to verify.

File: src/test/java/io/confluent/connect/jdbc/source/integration/PostgresOOMIT.java (hunk 5 above)
Comment (gharris1727) [reply src/test/java/io/confluent/connect/jdbc/source/integration/PostgresOOMIT.java]: The table monitor thread is in essentially the same relationship to this task as other tasks from the JDBC connector, and we don't see any issues from this running in production.
This is already effectively tested by running an existing source and sink connector in the same JVM, since sink connectors disable autocommit.

File: src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java [hunk 7]
```diff
@@ -81,13 +82,18 @@ public PostgreSqlDatabaseDialect(AbstractConfig config) {
...
+   * This will bound the memory usage of the connector for large tables.
+   *
    * @param stmt the prepared statement; never null
    * @throws SQLException the error that might result from initialization
    */
   @Override
   protected void initializePreparedStatement(PreparedStatement stmt) throws SQLException {
     log.trace("Initializing PreparedStatement fetch direction to FETCH_FORWARD for '{}'", stmt);
     stmt.setFetchDirection(ResultSet.FETCH_FORWARD);
+    stmt.setFetchSize(config.getInt(JdbcSourceConnectorConfig.BATCH_MAX_ROWS_CONFIG));
```
[the remark this answers is not in the document]
Comment (gharris1727) [reply src/main/java/io/confluent/connect/jdbc/dialect/PostgreSqlDatabaseDialect.java]: 1. As far as I understand, MySQL has a similar behavior, except that their url workaround is effective. I'm sure that theres at least one other database that we don't know about that has this same issue, and would require the same fix.

    However, without the abillity to integration test this functionality, I don't feel comfortable making changes to those dialects. Even for Postgres, I needed to find a way to integration test this change before I felt comfortable putting this up for PR. The cost to adding integration tests at this time is also higher than we can afford right now, and beyond the scope of this fix.

2. If someone included this URL option without knowing, then I don't think they would know/care that it was being ignored. Therefore, I'll assume that someone using this URL option put it there explicitly.

    If the URL option is higher than the batch size (perhaps by someone trying to optimize throughput) then it would be effectively the same as if it was equal the batch size except with higher memory usage. This is because the connector will still only read at most `batch.size` of data from the result set regardless of the fetch size.

    If the URL option was lower than the batch size (perhaps by someone trying to optimize memory) then they would notice that it didn't reduce memory usage. This would be non-obvious, but if they're optimizing memory usage, why would they change this URL parameter before reducing the batch size? Tuning the batch size performs effectively the same memory tuning behavior that they want, but it's actually supported by the connector itself, and documented behavior, rather than depending on this pass-through driver tuning parameter.

File: src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java (hunk 6 above)
Comment (gharris1727) [reply src/main/java/io/confluent/connect/jdbc/source/JdbcSourceTask.java]: Thank you for the call-out, this was a serious issue with that implementation. I've added a callback that disables autocommit for all new connections from that cached connection provider.

**Comment by gharris1727** [comment]
There are a few bug fixes/features which have added configuration options:

- `delete.enabled` https://github.com/confluentinc/kafka-connect-jdbc/pull/641
    This is arguable, since perhaps someone was relying on the error-on-null-value behavior, or wants to ensure that data is not deleted from their target system under any circumstances
- `quote.sql.identifiers` https://github.com/confluentinc/kafka-connect-jdbc/pull/572
    This could have been implemented without a config, but was included in order to maintain prior behavior for existing databases where data has already been transferred.
- `db.timezone` https://github.com/confluentinc/kafka-connect-jdbc/pull/505
    This definitely needs a configuration to give information about the database
- `connection.attempts`, `connection.backoff.ms`, https://github.com/confluentinc/kafka-connect-jdbc/pull/203
    This is a retry "feature", and it's reasonable to configure these to be more responsive or forgiving to network conditions
- `numeric.precision.mapping` https://github.com/confluentinc/kafka-connect-jdbc/pull/177 `numeric.mapping` https://github.com/confluentinc/kafka-connect-jdbc/pull/396
    This could have been implemented without a config, but was included in order to maintain prior behavior for existing databases where data has already been transferred.
- `schema.pattern` https://github.com/confluentinc/kafka-connect-jdbc/pull/109
    This definitely needs a configuration to give information about the database
- `validate.non.null` https://github.com/confluentinc/kafka-connect-jdbc/pull/51
    I think this shouldn't have been a configuration, and we should have just demoted this from an error to a warning. This is an example of a customer-specific configuration that isn't healthy long-term.

These are just the bug fixes that resulted in a configuration option, but there are many more that were fixed without a configuration option, many more than are listed here.

Overall, I think that the only justification for a configuration added as a bug fix is preservation of backwards compatibility, and I don't think that justification works here. Nobody is relying on the OOM exception as part of their workflow, and it has no impact on the actual data that's being transferred.

This is just the first dialect to have this fix applied, and applying it to each of them is simple. The only reason we're not adding them at this time is because of the cost of testing.
The last thing that I'd want is to add a configuration that is essentially a "throw OOM exception enable/disable" option, only to have it become obsolete after we make an investment and figure out which dialects can support it.

Let me know your thoughts @javabrett, and thanks for your review!

**Comment by yohei1126** [comment]
Hi, when new Docker images includes this fix is published to Docker hub?
https://hub.docker.com/r/confluentinc/cp-kafka-connect/tags
It looks like `latest` and `5.4.0` tags are already updated in a day ago but I do not know these tags include this fix.

**Comment by gharris1727** [comment]
This will not be released until the next patch release, so `5.3.3`, `5.4.1`, `5.5.0`, or `6.0.0`.
It will appear in docker images once those versions are released.
Until then you will need to build the connector from source in order to use this fix.

**Comment by kgrimsby** [comment]
Is this included in the latest confluent 5.4 deb packages?

**Comment by gharris1727** [comment]
@kgrimsby No, this will not be included in the 5.4 deb packages. It will be included in the deb packages of the versions I called out in my previous message.

**Comment by kgrimsby** [comment]
My bad @gharris1727 ! Sorry for wasting your time..
