### PR TITLE
CC-7265: Support SQL Server DateTimeOffset

### LINKED ISSUE #614: JDBC type -155 (datetimeoffset) not currently supported (io.confluent.connect.jdbc.dialect.SqlServerDatabaseDialect)
I am using kafka-connect-jdbc v 5.2.x. 

Ran into the following error when trying to test using timestamp columns that are of type datetimeoffset (JDBC Source connectors polling from SQL Server database mssql-jdbc-7.0.0.jre8.jar)

[2019-03-15 09:36:49,193] INFO WorkerSourceTask{id=datetimeoffset.ts.connector.test-0} Source task finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask)
[2019-03-15 09:36:49,193] INFO Attempting to open connection #1 to SqlServer (io.confluent.connect.jdbc.util.CachedConnectionProvider)
[2019-03-15 09:36:49,228] INFO Begin using SQL query: SELECT ID, Name, DateUpdated FROM test WHERE "DateUpdated" < ? AND (("DateUpdated" = ? AND "ID" > ?) OR "DateUpdated" > ?) ORDER BY "DateUpdated","ID" ASC (io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier)
[2019-03-15 09:36:49,267] **WARN JDBC type -155 (datetimeoffset) not currently supported (io.confluent.connect.jdbc.dialect.SqlServerDatabaseDialect)**
[2019-03-15 09:36:49,297] INFO Closing resources for JDBC source task (io.confluent.connect.jdbc.source.JdbcSourceTask)
[2019-03-15 09:36:49,298] INFO Closing connection #1 to SqlServer (io.confluent.connect.jdbc.util.CachedConnectionProvider)
[2019-03-15 09:36:49,298] INFO WorkerSourceTask{id=datetimeoffset.ts.connector.test-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask)
[2019-03-15 09:36:49,299] INFO WorkerSourceTask{id=datetimeoffset.ts.connector.test-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask)
[2019-03-15 09:36:49,299] ERROR WorkerSourceTask{id=datetimeoffset.ts.connector.test-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
**org.apache.kafka.connect.errors.DataException: DateUpdated is not a valid field name**
	at org.apache.kafka.connect.data.Struct.lookupField(Struct.java:254)
	at org.apache.kafka.connect.data.Struct.get(Struct.java:74)
	at io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.extractOffsetTimestamp(TimestampIncrementingCriteria.java:239)
	at io.confluent.connect.jdbc.source.TimestampIncrementingCriteria.extractValues(TimestampIncrementingCriteria.java:209)
	at io.confluent.connect.jdbc.source.TimestampIncrementingTableQuerier.extractRecord(TimestampIncrementingTableQuerier.java:196)
	at io.confluent.connect.jdbc.source.JdbcSourceTask.poll(JdbcSourceTask.java:318)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.poll(WorkerSourceTask.java:245)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:221)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:175)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:219)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2019-03-15 09:36:49,300] ERROR WorkerSourceTask{id=datetimeoffset.ts.connector.test-0} Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask)
[2019-03-15 09:36:49,301] INFO Stopping JDBC source task (io.confluent.connect.jdbc.source.JdbcSourceTask)

Can you please help?

Thanks.

### PR DESCRIPTION
**Pull request by rhauch**
Added support for SQL Server’s DateTimeOffset type. 

This change supports the jTDS driver that we ship by default, and even the latest version of this driver (which is pretty old) doesn't have support for DateTimeOffset. Per [MS documentation](https://docs.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql?redirectedfrom=MSDN&view=sql-server-ver15), the dialect handles DateTimeOffset values by getting the string form of the DateTimeOffset and parsing them into a Timestamp.

The MS SQL Server JDBC driver does support the DateTimeOffset type, so when this driver is used the dialect simply delegates to the driver to get the timestamp for the column.

Fixes #614 for `5.0.x` and later. See #752 for a fix for the `4.0.x` and `4.1.x` branches.

### CODE REVIEW

File: src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java [hunk 1]
```diff
@@ -242,8 +246,14 @@ public boolean isConnectionValid(
...
         if (statement.execute(query)) {
-          try (ResultSet rs = statement.getResultSet()) {
+          ResultSet rs = null;
+          try {
             // do nothing with the result set
+            rs = statement.getResultSet();
+          } finally {
+            if (rs != null) {
+              rs.close();
+            }
```
Comment (rhauch) [inline src/main/java/io/confluent/connect/jdbc/dialect/GenericDatabaseDialect.java]: This was changed to avoid a compilation warning about unreferenced autocloseable resource.
