### PR TITLE
Close all ResultSets in JdbcUtils.

### LINKED ISSUE #86: ORA-01000: maximum open cursors exceeded
I'm using kafka connect (Confluent platform v2.0.1) to pull data from Oracle db and getting the below error. Is there a connection leak?. Here's my job configuration:

```
{
  "name": "oracle-db-test",
  "config": {
    "connector.class": "io.confluent.connect.jdbc.JdbcSourceConnector",
    "tasks.max": "3",
    "connection.url": "jdbc:oracle:thin:user/password@hostname:port:dbname",
    "query": "SELECT * FROM TEST_DB",
    "mode": "timestamp",
    "timestamp.column.name": "MODIFIED_DATE",
    "topic.prefix": "test-topic"
  }
}
```

Error:

```
ERROR Error while trying to get updated table list, ignoring and waiting for next table poll interval (io.confluent.connect.jdbc.TableMonitorThread:107)
java.sql.SQLException: ORA-01000: maximum open cursors exceeded

    at oracle.jdbc.driver.SQLStateMapping.newSQLException(SQLStateMapping.java:70)
    at oracle.jdbc.driver.DatabaseError.newSQLException(DatabaseError.java:131)
    at oracle.jdbc.driver.DatabaseError.throwSqlException(DatabaseError.java:204)
    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:455)
    at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:413)
    at oracle.jdbc.driver.T4C8Oall.receive(T4C8Oall.java:1034)
    at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:194)
    at oracle.jdbc.driver.T4CPreparedStatement.executeForDescribe(T4CPreparedStatement.java:791)
    at oracle.jdbc.driver.T4CPreparedStatement.executeMaybeDescribe(T4CPreparedStatement.java:866)
    at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1186)
    at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:3387)
    at oracle.jdbc.driver.OraclePreparedStatement.executeQuery(OraclePreparedStatement.java:3431)
    at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeQuery(OraclePreparedStatementWrapper.java:1203)
    at oracle.jdbc.OracleDatabaseMetaData.getTables(OracleDatabaseMetaData.java:2503)
    at io.confluent.connect.jdbc.JdbcUtils.getTables(JdbcUtils.java:90)
    at io.confluent.connect.jdbc.JdbcUtils.getTables(JdbcUtils.java:79)
    at io.confluent.connect.jdbc.TableMonitorThread.updateTables(TableMonitorThread.java:105)
    at io.confluent.connect.jdbc.TableMonitorThread.run(TableMonitorThread.java:61)
```

### PR DESCRIPTION
**Pull request by ewencp**
Fixes #86

### CODE REVIEW

**Comment by ewencp** [comment]
@confluentinc/connect Ping for review

File: src/main/java/io/confluent/connect/jdbc/JdbcUtils.java [hunk 1]
```diff
@@ -92,16 +92,20 @@ protected SimpleDateFormat initialValue() {
     DatabaseMetaData metadata = conn.getMetaData();
     ResultSet rs = metadata.getTables(null, null, "%", null);
     List<String> tableNames = new ArrayList<>();
-    while (rs.next()) {
-      if (types.contains(rs.getString(GET_TABLES_TYPE_COLUMN))) {
-        String colName = rs.getString(GET_TABLES_NAME_COLUMN);
-        // SQLite JDBC driver does not correctly mark these as system tables
-        if (metadata.getDatabaseProductName().equals("SQLite") && colName.startsWith("sqlite_")) {
-          continue;
+    try {
```
Comment (hachikuji) [inline src/main/java/io/confluent/connect/jdbc/JdbcUtils.java]: Looks like we ought to be able to use a "try with resources" block.

Comment (ewencp) [inline src/main/java/io/confluent/connect/jdbc/JdbcUtils.java]: Excellent point... I may be somewhat stuck in the mode of writing JDK6 compatible code. In fact, even more of this can be simplified since `ResultSet` is automatically closed when its statement is closed, so I've updated to handle all the `try` blocks to use try with resources on the `Statement` where one is explicitly created and on the `ResultSet` for the ones returned by `DatabaseMetadata` calls.

**Comment by hachikuji** [comment]
LGTM
